name: Azure Storage Static Website CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # [핵심] 에러 주범이었던 SWA 단계를 삭제하고 스토리지 배포만 남겼습니다.
      - name: Deploy to Azure Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch -s ./ -d '$web' --account-name snow2storage --auth-mode key --overwrite true --account-key ${{ secrets.AZURE_STORAGE_KEY }}